export declare class GoalService {
    listGoals(workspaceId: string): Promise<{
        id: string;
        metadata: import("@prisma/client/runtime/library").JsonValue | null;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        version: number;
        workspaceId: string;
        createdBy: string | null;
        updatedBy: string | null;
        title: string;
        type: string;
        spaceId: string | null;
        progress: number;
        targetDate: Date | null;
        parentGoalId: string | null;
    }[]>;
    getGoal(id: string, workspaceId: string): Promise<{
        id: string;
        metadata: import("@prisma/client/runtime/library").JsonValue | null;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        version: number;
        workspaceId: string;
        createdBy: string | null;
        updatedBy: string | null;
        title: string;
        type: string;
        spaceId: string | null;
        progress: number;
        targetDate: Date | null;
        parentGoalId: string | null;
    }>;
    createGoal(data: any, userId: string): Promise<{
        id: string;
        metadata: import("@prisma/client/runtime/library").JsonValue | null;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        version: number;
        workspaceId: string;
        createdBy: string | null;
        updatedBy: string | null;
        title: string;
        type: string;
        spaceId: string | null;
        progress: number;
        targetDate: Date | null;
        parentGoalId: string | null;
    }>;
    updateGoal(id: string, workspaceId: string, data: any, userId: string): Promise<{
        id: string;
        metadata: import("@prisma/client/runtime/library").JsonValue | null;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        version: number;
        workspaceId: string;
        createdBy: string | null;
        updatedBy: string | null;
        title: string;
        type: string;
        spaceId: string | null;
        progress: number;
        targetDate: Date | null;
        parentGoalId: string | null;
    }>;
    deleteGoal(id: string, workspaceId: string, userId: string): Promise<{
        id: string;
        metadata: import("@prisma/client/runtime/library").JsonValue | null;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        version: number;
        workspaceId: string;
        createdBy: string | null;
        updatedBy: string | null;
        title: string;
        type: string;
        spaceId: string | null;
        progress: number;
        targetDate: Date | null;
        parentGoalId: string | null;
    }>;
    restoreGoal(id: string, workspaceId: string, userId: string): Promise<{
        id: string;
        metadata: import("@prisma/client/runtime/library").JsonValue | null;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        version: number;
        workspaceId: string;
        createdBy: string | null;
        updatedBy: string | null;
        title: string;
        type: string;
        spaceId: string | null;
        progress: number;
        targetDate: Date | null;
        parentGoalId: string | null;
    }>;
}
export declare const goalService: GoalService;
//# sourceMappingURL=goal.service.d.ts.map
