name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: krama_user
          POSTGRES_PASSWORD: krama_password
          POSTGRES_DB: krama_os
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.0.0

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma Client
        run: |
          cd apps/server
          npx prisma generate

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Setup Prisma DB
        run: |
          cd apps/server
          npx prisma migrate deploy
        env:
          DATABASE_URL: "postgresql://krama_user:krama_password@localhost:5433/krama_os?schema=public"

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E Tests
        run: npx playwright test
        env:
          DATABASE_URL: "postgresql://krama_user:krama_password@localhost:5433/krama_os?schema=public"
          REDIS_URL: "redis://localhost:6379"
          JWT_SECRET: "krama_super_secret_jwt_key_2026"
          PORT: 3000

